CiCdAzureDevOps/Controllers/HomeController.cs
using System.Web.Mvc;

namespace CiCdAzureDevOps.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

CiCdAzureDevOps/Controllers/ShohagController.cs
using System.Web.Mvc;

namespace CiCdAzureDevOps.Controllers
{
    public class ShohagController : Controller
    {
        // GET: Shohag
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult About()
        {
            return View();
        }
        public ActionResult Contact()
        {
            return View();
        }
    }
}

CiCdAzureDevOps/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Welcome to Shohag's Apps</h2>

CiCdAzureDevOps/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Shohag's Apps", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Shohag")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Shohag")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

CiCdAzureDevOps/Views/Shohag/About.cshtml
@{
    ViewBag.Title = "About";
}

<h2>Shohag's About</h2>

CiCdAzureDevOps/Views/Shohag/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<h2>Shohag's Contact</h2>

CiCdAzureDevOps/Views/Shohag/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Md Shohag Mia</h2>